### ISSUE TITLE
Script failed while installing mujoco_py

### ISSUE THREAD

**Issue by mweber7** [andrewschreiber/scripts#3]
See below for an excerpt of the received error:

fatal error: mjmodel.h: No such file or directory
   #include "mjmodel.h"
            ^~~~~~~~~~~
  compilation terminated.
  error: command '/usr/local/bin/gcc-7' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py, gym
  Running setup.py install for mujoco-py ... error
    Complete output from command /Applications/anaconda/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-qs6444fq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mujoco_py.cymj' extension
    /usr/local/bin/gcc-7 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/anaconda/envs/p35/include -arch x86_64 -I/Applications/anaconda/envs/p35/include -arch x86_64 -DONMAC -Imujoco_py -I/private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/mujoco_py -I/Users/mweber/.mujoco/mjpro150/include -I/Applications/anaconda/envs/p35/lib/python3.5/site-packages/numpy/core/include -I/Applications/anaconda/envs/p35/include/python3.5m -c /private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/mujoco_py/cymj.c -o /private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/mujoco_py/generated/_pyxbld_MacExtensionBuilder/temp.macosx-10.6-x86_64-3.5/private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    /private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/mujoco_py/cymj.c:573:10: fatal error: mjmodel.h: No such file or directory
     #include "mjmodel.h"
              ^~~~~~~~~~~
    compilation terminated.
    error: command '/usr/local/bin/gcc-7' failed with exit status 1
    
    ----------------------------------------
Command "/Applications/anaconda/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-qs6444fq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rv/7r2c88sx7kbgcgb605v0116c0000gn/T/pip-build-mw16rf7s/mujoco-py/

**Comment by andrewschreiber** [comment]
Hmm seems like a Python 3 issue with mujoco. Relevant OpenAI Gym issue https://github.com/openai/mujoco-py/issues/43. This may be due to Gym moving to 3.6, while this repo is still on 3.5. I'll experiment.

**Comment by dfrankow** [comment]
I got an error installing `mujoco-py` but it's different.

```
Successfully built gym PyOpenGL imageio future glfw pycparser
Failed to build mujoco-py
Installing collected packages: scipy, idna, chardet, urllib3, requests, future, pyglet, atari-py, Pillow, PyOpenGL, glfw, Cython, imageio, pycparser, cffi, lockfile, mujoco-py, box2d-py, gym
  Running setup.py install for mujoco-py ... error
    Complete output from command /Users/dan/miniconda3/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-record-4lzs0spv/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /Users/dan/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /Users/dan/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    
    ----------------------------------------
Command "/Users/dan/miniconda3/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-record-4lzs0spv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/
```

**Comment by seth-johnson-sp** [comment]
> I got an error installing `mujoco-py` but it's different.
> 
> ```
> Successfully built gym PyOpenGL imageio future glfw pycparser
> Failed to build mujoco-py
> Installing collected packages: scipy, idna, chardet, urllib3, requests, future, pyglet, atari-py, Pillow, PyOpenGL, glfw, Cython, imageio, pycparser, cffi, lockfile, mujoco-py, box2d-py, gym
>   Running setup.py install for mujoco-py ... error
>     Complete output from command /Users/dan/miniconda3/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-record-4lzs0spv/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     
>     You appear to be missing MuJoCo.  We expected to find the file here: /Users/dan/.mujoco/mjpro150
>     
>     This package only provides python bindings, the library must be installed separately.
>     
>     Please follow the instructions on the README to install MuJoCo
>     
>         https://github.com/openai/mujoco-py#install-mujoco
>     
>     Which can be downloaded from the website
>     
>         https://www.roboti.us/index.html
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py", line 44, in <module>
>         tests_require=read_requirements_file('requirements.dev.txt'),
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
>         return distutils.core.setup(**attrs)
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/command/install.py", line 539, in run
>         self.run_command('build')
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/Users/dan/miniconda3/envs/p35/lib/python3.5/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py", line 28, in run
>         import mujoco_py  # noqa: force build
>       File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
>         from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
>       File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/builder.py", line 502, in <module>
>         mjpro_path, key_path = discover_mujoco()
>       File "/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
>         raise Exception(message)
>     Exception:
>     You appear to be missing MuJoCo.  We expected to find the file here: /Users/dan/.mujoco/mjpro150
>     
>     This package only provides python bindings, the library must be installed separately.
>     
>     Please follow the instructions on the README to install MuJoCo
>     
>         https://github.com/openai/mujoco-py#install-mujoco
>     
>     Which can be downloaded from the website
>     
>         https://www.roboti.us/index.html
>     
>     
>     ----------------------------------------
> Command "/Users/dan/miniconda3/envs/p35/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-record-4lzs0spv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/t6/6fyvgz7x5dg3x4qlk58cmrmw0000gn/T/pip-install-eq1szvae/mujoco-py/
> ```

Same issue for me. Looks like the muJoCo package is commercial and they have some cumbersome licensing mechanism that requires running a strange application to gather a computer ID, etc. etc. I'd recommend pulling the mujoco package from this installer as your script fundamentally doesn't work now.

**Comment by ha7008** [comment]
I am using Catalina 10.15.3 on a macbook air.

I had multiple problems installing everything, but to be able to install MuJoCo I had to get their license through their website ( https://www.roboti.us/license.html )
Fortunately I'm a student so I could get it for free. After that I downloaded MuJoCo200 from the website for mac and I had to use the terminal to UNZIP it the right way and put the license in the right place. They say this on their github ( https://github.com/openai/mujoco-py ), but it wasn't very clear how to do it, what commands to use etc, so I googled that.

Before I could install MuJoCo though, I had to install gcc using " brew install gcc " which took a very long time (more than an hour, maybe two) but solved most of my problems. (And for this you first need to install homebrew but I had it installed since before) Don't panic if it seems like the computer "stops" and does nothing while installing gcc, it is still working. And it also it gets really hot so if you have an external computer fan that might be good to use.

After installing gcc and placing all the MuJoCo-files in the right place, I could eventually install it using:
pip3 install -U 'mujoco-py<2.1,>=2.0' --no-use-pep517

the "--no-use-pep517" was needed. I don't remember exactly why but it had something to do with a new update of pip.

Also, through multiple steps I was not allowed to do things because of my macbook's security preferences (in the privacy tab), so I had to give the terminal full disc access and full access to developer tools. You do this by klicking on the lock at the bottom left corner and then choosing the terminal for both these things.

I also had to update Xcode through the appstore for some reason, I did this in the beginning of my journey, and you might have to do this too but I don't remember exactly why.

After all of this I could use Andrew's script and it worked.

I have spent near 20hrs to solve all my problems, and there might be a thing or two that I forgot, but I hope that this can help anyone who have similar problems.
